metadata:
  title: "每日新闻"
  subtitle: ""
  author: "KMMoonlight"
  email: "kmmoonlight@outlook.com"
  description: "Daily News"
  link: "https://kmmoonlight.github.io/podcast-rss-generator"
  rss_feed_url: "https://kmmoonlight.github.io/podcast-rss-generator/rss.xml"
  language: zh-CN
  explicit: false
  copyright: "© 2025 KMMoonlight"
  image: "https://github.com/kmmoonlight/podcast-rss-generator/raw/main/cover.jpg"
  categories:
    - "News"
  owner:
    name: "KMMoonlight"
    email: "kmmoonlight@outlook.com"
episodes:
  - title: "2025-11-30"
    description: "2025/11/30 新闻"
    date: 2025-11-30
    publication_date: "2025-11-30T02:30:00Z"
    duration: "00:05:03"
    asset_url: "https://github.com/kmmoonlight/podcast-rss-generator/releases/download/v1.0/2025-11-30.mp3"
    explicit: false
    season: 1
    episode: 1
    type: full
